services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db-complejo-deportivo
    restart: always
    environment:
      POSTGRES_USER: limber
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bdcomplejodeportivo
      TZ: America/La_Paz
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U limber -d bdcomplejodeportivo"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: sports_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sports.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: sports_backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: sports_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000/api
    depends_on:
      - backend

volumes:
  pgdata: